const data = [
	`2001: A Space Odyssey`,
	`A Clockwork Orange`,
	`A Night at the Opera`,
	`A Streetcar Named Desire`,
	`All About Eve`,
	`All the President's Men`,
	`American Graffiti`,
	`Angry Men`,
	`Annie Hall`,
	`Apocalypse Now`,
	`Ben-Hur`,
	`Blade Runner`,
	`Bonnie and Clyde`,
	`Bringing Up Baby`,
	`Butch Cassidy and the Sundance Kid`,
	`Cabaret`,
	`Casablanca`,
	`Chinatown`,
	`Citizen Kane`,
	`City Lights`,
	`Do the Right Thing`,
	`Double Indemnity`,
	`Dr. Strangelove`,
	`Duck Soup`,
	`E.T. the Extra-Terrestrial`,
	`Easy Rider`,
	`Forrest Gump`,
	`Gone with the Wind`,
	`Goodfellas`,
	`High Noon`,
	`In the Heat of the Night`,
	`Intolerance`,
	`It Happened One Night`,
	`It's a Wonderful Life`,
	`Jaws`,
	`King Kong`,
	`Lawrence of Arabia`,
	`M*A*S*H`,
	`Midnight Cowboy`,
	`Modern Times`,
	`Mr. Smith Goes to Washington`,
	`Nashville`,
	`Network`,
	`North by Northwes`,
	`On the Waterfront`,
	`One Flew Over the Cuckoo's Nest`,
	`Platoon`,
	`Psycho`,
	`Pulp Fiction`,
	`Raging Bull`,
	`Raiders of the Lost Ark`,
	`Rear Window`,
	`Rocky`,
	`Saving Private Ryan`,
	`Schindler's List`,
	`Shane`,
	`Singin' in the Rain`,
	`Snow White and the Seven Dwarfs`,
	`Some Like It Hot`,
	`Sophie's Choice`,
	`Spartacus`,
	`Star Wars`,
	`Sullivan's Travels`,
	`Sunrise: A Song of Two Humans`,
	`Sunset Boulevard`,
	`Swing Time`,
	`Taxi Driver`,
	`The African Queen`,
	`The Apartment`,
	`The Best Years of Our Lives`,
	`The Bridge on the River Kwai`,
	`The Deer Hunter`,
	`The French Connection`,
	`The General`,
	`The Godfather Part II`,
	`The Godfather`,
	`The Gold Rush`,
	`The Graduate`,
	`The Grapes of Wrath`,
	`The Last Picture Show`,
	`The Lord of the Rings: The Fellowship of the Ring`,
	`The Maltese Falcon`,
	`The Philadelphia Story`,
	`The Searchers`,
	`The Shawshank Redemption`,
	`The Silence of the Lambs`,
	`The Sixth Sense`,
	`The Sound of Music`,
	`The Treasure of the Sierra Madre`,
	`The Wild Bunch`,
	`The Wizard of Oz`,
	`Titanic`,
	`To Kill a Mockingbird`,
	`Tootsie`,
	`Toy Story`,
	`Unforgiven`,
	`Vertigo`,
	`West Side Story`,
	`Who's Afraid of Virginia Woolf?`,
	`Yankee Doodle Dandy`,
];

export default data;
